### ISSUE TITLE
First review checklist

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/builder-profile-maker#3]
The first page uses the orange color theme, which I like, but this should be changed as a theme color for the whole app rather than the green.

### Page 1

![image](https://github.com/user-attachments/assets/bcb1c10e-4902-4ec1-adf9-127ba15735a8)

- [x] remove near address input from first page, we'll get this from the login later
- [x] floating hat to the right
- [x] decision of upper left Build DAO vs Build DAO above "Builder Profile Creator" or "Profile Builder"

### Page 2

The old, two columns was nice. We can find a replacement image for the left, or just use what was already there. Let's add it back.

- [ ] Add back two column split
- [ ] Replace Profile Image URL and Background Image URL with image uploads, use upload thing, you can pull code from the Next-js landing page revamp.

### Page 3

- [ ] Remove Facebook, Pinterest, Reddit, Tiktok, Codepen, Discord, Instagram, Medium, Quora, StackOverflow, Youtube, Mastadon

### Page 4

For languages, remove anything that isn't Javascript, Rust, C#, GraphQL, HTML5, Java, Kotlin, PHP, Ruby, Rust, Solidity, Typscript, Zig

Let's remove hosting section, comment out, we might reuse...

For the rest of the stuff, may want to think what we actually want to do with these tags

### Page 5

We can maybe remove the donate page... comment out

### Page 6 

We'll have to think of the preview -- we can maybe embed the near social profile on there. We should prompt the users

Have a NEAR account? Login

Need a NEAR account? Create one (https://shard.dog/nearweek)
